# Generated by Django 4.1.4 on 2023-01-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='imageURL',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='spotifyID',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
