# Generated by Django 4.1.4 on 2023-04-06 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_alter_appuser_imageurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appuser',
            old_name='imageURL',
            new_name='profileImageUrl',
        ),
    ]
