# Generated by Django 4.1.4 on 2023-04-10 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_rename_imageurl_appuser_profileimageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='profileImageUrl',
            field=models.TextField(default='https://i.ibb.co/Zgcdrfj/profile-image.png'),
        ),
    ]
